definitions:
  models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  models.Note:
    type: object
  models.NoteResponse:
    properties:
      data:
        $ref: '#/definitions/models.Note'
      message:
        type: string
    type: object
  models.Notes:
    properties:
      notes:
        items:
          $ref: '#/definitions/models.Note'
        type: array
    type: object
  models.UpdateNote:
    properties:
      description:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/notes:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all notes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Notes'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all notes
      tags:
      - notes
    post:
      consumes:
      - application/json
      description: Create a new note with the provided data
      parameters:
      - description: Note data
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/models.Note'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.NoteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a new note
      tags:
      - notes
  /api/notes/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a note by ID
      parameters:
      - description: Note ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NoteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete a note
      tags:
      - notes
    get:
      consumes:
      - application/json
      description: Get details of a specific note by its ID
      parameters:
      - description: Note ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Note'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get note by ID
      tags:
      - notes
    patch:
      consumes:
      - application/json
      description: Update an existing note by ID
      parameters:
      - description: Note ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated note data
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/models.UpdateNote'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NoteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update a note
      tags:
      - notes
swagger: "2.0"
